//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutterFace.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShutterFace.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ShutterFace ähnelt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Tracking Point ähnelt.
        /// </summary>
        internal static string BtnAddTracking {
            get {
                return ResourceManager.GetString("BtnAddTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyze ähnelt.
        /// </summary>
        internal static string BtnAnalyze {
            get {
                return ResourceManager.GetString("BtnAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Tracking ähnelt.
        /// </summary>
        internal static string BtnDeleteTracking {
            get {
                return ResourceManager.GetString("BtnDeleteTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save ähnelt.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Analyzing ähnelt.
        /// </summary>
        internal static string BtnStopAnalyzing {
            get {
                return ResourceManager.GetString("BtnStopAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete this tracking rectangle? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteTracking {
            get {
                return ResourceManager.GetString("ConfirmDeleteTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have unsaved changes. Do you want to save before closing? ähnelt.
        /// </summary>
        internal static string ConfirmUnsavedChanges {
            get {
                return ResourceManager.GetString("ConfirmUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Face ähnelt.
        /// </summary>
        internal static string DefaultTrackingNamePrefix {
            get {
                return ResourceManager.GetString("DefaultTrackingNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error exporting video: {0} ähnelt.
        /// </summary>
        internal static string ErrExportVideo {
            get {
                return ResourceManager.GetString("ErrExportVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error loading tracking data: {0} ähnelt.
        /// </summary>
        internal static string ErrLoadTrackingData {
            get {
                return ResourceManager.GetString("ErrLoadTrackingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving tracking data: {0} ähnelt.
        /// </summary>
        internal static string ErrSaveTrackingData {
            get {
                return ResourceManager.GetString("ErrSaveTrackingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting video... ähnelt.
        /// </summary>
        internal static string ExportingVideoTitle {
            get {
                return ResourceManager.GetString("ExportingVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;File ähnelt.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video Files|*.mp4|All Files|*.* ähnelt.
        /// </summary>
        internal static string FilterSaveVideo {
            get {
                return ResourceManager.GetString("FilterSaveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ShutterFace Project|*.sft|All Files|*.* ähnelt.
        /// </summary>
        internal static string FilterProjectFiles {
            get {
                return ResourceManager.GetString("FilterProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video Files|*.mp4;*.avi;*.mov;*.wmv;*.mkv;*.flv;*.webm|All Files|*.* ähnelt.
        /// </summary>
        internal static string FilterVideoFiles {
            get {
                return ResourceManager.GetString("FilterVideoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Form_Settings {
            get {
                return ResourceManager.GetString("Form_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blur Settings ähnelt.
        /// </summary>
        internal static string GroupBlur {
            get {
                return ResourceManager.GetString("GroupBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking Settings ähnelt.
        /// </summary>
        internal static string GroupTracking {
            get {
                return ResourceManager.GetString("GroupTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking Properties ähnelt.
        /// </summary>
        internal static string GroupTrackingProperties {
            get {
                return ResourceManager.GetString("GroupTrackingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big Pixels (longest side): ähnelt.
        /// </summary>
        internal static string LabelBigPixels {
            get {
                return ResourceManager.GetString("LabelBigPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grid Cell Size: (~5% des Bildes) ähnelt.
        /// </summary>
        internal static string LabelGridCellSize {
            get {
                return ResourceManager.GetString("LabelGridCellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blurring: ähnelt.
        /// </summary>
        internal static string LabelBlurring {
            get {
                return ResourceManager.GetString("LabelBlurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confidence Threshold: ähnelt.
        /// </summary>
        internal static string LabelConfidenceThreshold {
            get {
                return ResourceManager.GetString("LabelConfidenceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --:--:-- ähnelt.
        /// </summary>
        internal static string LabelDefaultTime {
            get {
                return ResourceManager.GetString("LabelDefaultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End Fr.: ähnelt.
        /// </summary>
        internal static string LabelEndFrame {
            get {
                return ResourceManager.GetString("LabelEndFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height: ähnelt.
        /// </summary>
        internal static string LabelHeight {
            get {
                return ResourceManager.GetString("LabelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Fr.: ähnelt.
        /// </summary>
        internal static string LabelStartFrame {
            get {
                return ResourceManager.GetString("LabelStartFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string LabelTrackingName {
            get {
                return ResourceManager.GetString("LabelTrackingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width: ähnelt.
        /// </summary>
        internal static string LabelWidth {
            get {
                return ResourceManager.GetString("LabelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;English ähnelt.
        /// </summary>
        internal static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Deutsch ähnelt.
        /// </summary>
        internal static string LangGerman {
            get {
                return ResourceManager.GetString("LangGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Language ähnelt.
        /// </summary>
        internal static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;About ähnelt.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E&amp;xit ähnelt.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Export Video ähnelt.
        /// </summary>
        internal static string MenuExportVideo {
            get {
                return ResourceManager.GetString("MenuExportVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Load Project ähnelt.
        /// </summary>
        internal static string MenuLoadProject {
            get {
                return ResourceManager.GetString("MenuLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Open Video ähnelt.
        /// </summary>
        internal static string MenuOpenVideo {
            get {
                return ResourceManager.GetString("MenuOpenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save Project ähnelt.
        /// </summary>
        internal static string MenuSaveProject {
            get {
                return ResourceManager.GetString("MenuSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Settings ähnelt.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysis stopped at frame {0} - object lost ähnelt.
        /// </summary>
        internal static string MsgAnalysisObjectLost {
            get {
                return ResourceManager.GetString("MsgAnalysisObjectLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click and drag on the video to create a tracking rectangle. ähnelt.
        /// </summary>
        internal static string MsgClickDragTracking {
            get {
                return ResourceManager.GetString("MsgClickDragTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load tracking data. ähnelt.
        /// </summary>
        internal static string MsgFailedToLoadTracking {
            get {
                return ResourceManager.GetString("MsgFailedToLoadTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loaded {0} tracking rectangles successfully! ähnelt.
        /// </summary>
        internal static string MsgLoadedTracks {
            get {
                return ResourceManager.GetString("MsgLoadedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No tracking data to save. ähnelt.
        /// </summary>
        internal static string MsgNoTrackingToSave {
            get {
                return ResourceManager.GetString("MsgNoTrackingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No video loaded to export. ähnelt.
        /// </summary>
        internal static string MsgNoVideoLoaded {
            get {
                return ResourceManager.GetString("MsgNoVideoLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a tracking point first. ähnelt.
        /// </summary>
        internal static string MsgSelectTrackingFirst {
            get {
                return ResourceManager.GetString("MsgSelectTrackingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start frame cannot be after end frame. Adjusting values. ähnelt.
        /// </summary>
        internal static string MsgStartFrameAfterEnd {
            get {
                return ResourceManager.GetString("MsgStartFrameAfterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking data saved successfully! ähnelt.
        /// </summary>
        internal static string MsgTrackingSaved {
            get {
                return ResourceManager.GetString("MsgTrackingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking properties updated successfully! ähnelt.
        /// </summary>
        internal static string MsgTrackingUpdated {
            get {
                return ResourceManager.GetString("MsgTrackingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track range: Frame {0} to {1} ähnelt.
        /// </summary>
        internal static string MsgTrackRange {
            get {
                return ResourceManager.GetString("MsgTrackRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are {0} unanalyzed tracking(s). Do you want to analyze them before exporting? ähnelt.
        /// </summary>
        internal static string MsgUnanalyzedTracksExport {
            get {
                return ResourceManager.GetString("MsgUnanalyzedTracksExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The original video file was not found. Please open the video manually. ähnelt.
        /// </summary>
        internal static string MsgVideoNotFound {
            get {
                return ResourceManager.GetString("MsgVideoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The original video file was not found. Please open the video manually. ähnelt.
        /// </summary>
        internal static string MsgVideoNotFoundOpenManual {
            get {
                return ResourceManager.GetString("MsgVideoNotFoundOpenManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video dimensions differ from saved project. ähnelt.
        /// </summary>
        internal static string MsgVideoDimensionsChanged {
            get {
                return ResourceManager.GetString("MsgVideoDimensionsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyzing: {0} ähnelt.
        /// </summary>
        internal static string StatusAnalyzing {
            get {
                return ResourceManager.GetString("StatusAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyzing complete for {0} ähnelt.
        /// </summary>
        internal static string StatusAnalyzingComplete {
            get {
                return ResourceManager.GetString("StatusAnalyzingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export complete ähnelt.
        /// </summary>
        internal static string StatusExportComplete {
            get {
                return ResourceManager.GetString("StatusExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string StatusExporting {
            get {
                return ResourceManager.GetString("StatusExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}% complete ähnelt.
        /// </summary>
        internal static string StatusExportingProgress {
            get {
                return ResourceManager.GetString("StatusExportingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}% ähnelt.
        /// </summary>
        internal static string StatusExportingProgressFormat {
            get {
                return ResourceManager.GetString("StatusExportingProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frame: {0}/{1} ähnelt.
        /// </summary>
        internal static string StatusFrameCount {
            get {
                return ResourceManager.GetString("StatusFrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Built with OpenCode (qwen3.6-35b-128k) ähnelt.
        /// </summary>
        internal static string SubtitleAbout {
            get {
                return ResourceManager.GetString("SubtitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ShutterFace ähnelt.
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unanalyzed Tracks ähnelt.
        /// </summary>
        internal static string TitleUnanalyzedTracks {
            get {
                return ResourceManager.GetString("TitleUnanalyzedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved Changes ähnelt.
        /// </summary>
        internal static string TitleUnsavedChanges {
            get {
                return ResourceManager.GetString("TitleUnsavedChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detect Faces ähnelt.
        /// </summary>
        internal static string BtnDetectFaces {
            get {
                return ResourceManager.GetString("BtnDetectFaces", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No untracked faces detected in this frame. ähnelt.
        /// </summary>
        internal static string MsgNoNewFaces {
            get {
                return ResourceManager.GetString("MsgNoNewFaces", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detected {0} new face(s), added as tracking point(s). ähnelt.
        /// </summary>
        internal static string MsgNewFacesDetected {
            get {
                return ResourceManager.GetString("MsgNewFacesDetected", resourceCulture);
            }
        }
    }
}
